### ISSUE TITLE
Newark-WTC line running in two sections on 2/20/22

### ISSUE THREAD

**Issue by deegoldberg** [mrazza/path-data#13]
This weekend the Newark-WTC line is running in two sections. I'm wondering if PANYNJ has assigned the two sections unique IDs that need to be handled by the API?

**Comment by mrazza** [comment]
The SQL database provided by PATH has no entry for the this route. I.E. Headsign and color does not match any routes in the database.

```
2022-02-20 22:11:27.391 +00:00 [Warning] (/SignalRRealtimeDataRepository.ProcessNewMessage:160) Failed to lookup route during realtime message update.
System.Collections.Generic.KeyNotFoundException: Could not find route with headsign=Journal Square and color=D93A30.
   at PathApi.Server.PathServices.PathSqlDbRepository.GetRouteFromTrainHeadsign(String headsignName, IEnumerable`1 headsignColors) in /home/mrazza/sources/path-data/server/PathServices/PathSqlDbRepository.cs:line 239
   at PathApi.Server.PathServices.SignalRRealtimeDataRepository.<>c__DisplayClass10_0.<b__1>d.MoveNext() in /home/mrazza/sources/path-data/server/PathServices/SignalRRealtimeDataRepository.cs:line 164
```

Given that the realtime data PATH is generating does not match the SQL database they're using, there's nothing to do. I could, of course, hardcode some mapping for this specific case but weird one-off PATH behavior doesn't seem worth accounting for each time PATH does something unique. If they don't bother putting it in the database, I don't think the API should bother offering first-class support. The realtime data is still available, just with unknown route information.

```
{
   "lineName": "Journal Square",
   "headsign": "Journal Square",
   "route": "ROUTE_UNSPECIFIED",
   "routeDisplayName": "",
   "direction": "DIRECTION_UNSPECIFIED",
   "lineColors": [
    "#D93A30"
   ],
   "status": "ON_TIME",
   "projectedArrival": "2022-02-20T22:20:54Z",
   "lastUpdated": "2022-02-20T22:10:41Z"
  },
```
