### ISSUE TITLE
Startup failure: failure to load database

### ISSUE THREAD

**Issue by mrazza** [mrazza/path-data#8]
Investigation required.

```
2021-06-11 04:28:21.968 +00:00 [Information] (/StartupTaskExecutor.ExecuteTasks:38) Executing startup tasks...
2021-06-11 04:28:21.991 +00:00 [Information] (/PathSqlDbRepository.OnStartup:69) Preparing PATH SQL repository...
2021-06-11 04:28:22.639 +00:00 [Information] (/PathApiClient.GetLatestChecksum:44) PATH DB checksum updated to "CE78A735F3DCF2CCB49E546CF40F9E29".
Unhandled Exception: System.AggregateException: One or more errors occurred. (Invalid response from PATH API when downloading DB update: NotFound) ---> System.Net.Http.HttpRequestException: Invalid response from PATH API when downloading DB update: NotFound
   at PathApi.Server.PathServices.PathApiClient.GetDatabaseAsStream(String checksum) in /home/mrazza/sources/path-data/server/PathServices/PathApiClient.cs:line 66
   at PathApi.Server.PathServices.PathSqlDbRepository.DownloadDatabase() in /home/mrazza/sources/path-data/server/PathServices/PathSqlDbRepository.cs:line 299
   at PathApi.Server.PathServices.PathSqlDbRepository.OnStartup() in /home/mrazza/sources/path-data/server/PathServices/PathSqlDbRepository.cs:line 73
   at PathApi.Server.StartupTaskExecutor.ExecuteTasks() in /home/mrazza/sources/path-data/server/StartupTaskExecutor.cs:line 39
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PathApi.Server.Program.Main(String[] args) in /home/mrazza/sources/path-data/server/Program.cs:line 41
```

**Comment by mrazza** [comment]
Seems to have fixed itself. Unclear why.
